### ISSUE TITLE
Disabled & Delete Comments

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-user-profile-avatar#25]
Please find below reference and try to add same like this plugin

https://wordpress.org/plugins/disable-comments/

![screenshot-1](https://user-images.githubusercontent.com/15089059/90868358-0b74eb00-e397-11ea-9476-e431b3acf51d.png)

![screenshot-2](https://user-images.githubusercontent.com/15089059/90868365-0dd74500-e397-11ea-9082-b4e427c68fc4.png)

You need to adjust with our coding style and plugin structure.

Other References:

https://wordpress.org/plugins/disable-comments/
https://wordpress.org/plugins/disable-comments-permanently-in-one-click/
https://wordpress.org/plugins/disable-comments-rb/
https://kinsta.com/blog/wordpress-disable-comments/

**Comment by hiteshmakvana** [comment]
Still there is same errors

![image](https://user-images.githubusercontent.com/42602299/96336434-6b3cf900-109d-11eb-9219-a92434baefb3.png)

**Comment by mistry-jignesh** [comment]
Verified this issue.Now this error message issue is fixed.
 
So I closed the issue.

**Comment by krinaydhanani** [comment]
This issue is still not fixed properly. When I disable the option from the setting, the comment section is not visible on the fronted side. Please fix this issue.

**Comment by mistry-jignesh** [comment]
I need to check again. I am still facing issue with a comment section.

**Comment by mistry-jignesh** [comment]
I have verified this issue. 
Comment diable & delete follow is working fine.
So I closed the issue.
